### PR TITLE
ios: fix build

### PR DESCRIPTION
**Pull request by saentari**
Proposed solution to [issue #64 - App does not build for iOS](https://github.com/dart-lightning/lndart.clnapp/issues/64).

Fixes https://github.com/dart-lightning/lndart.clnapp/issues/64

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Looks good, just to change the commit header to help us to autogenerate the changelog.

Somethings like that would be good `fix: fix build for ios`, the motivation is described in https://github.com/dart-lightning/lndart.clnapp/blob/main/docs/dev/MAINTAINERS.md#commit-style

**Comment by saentari** [comment]
Hopefully, the change commit is correct now.

**Comment by vincenzopalazzo** [comment]
There is a minor CI failure that it looks unrelated to your PR, but can you fix also this? :)

```
Run flutter analyze .
Analyzing lndart.clnapp...                                      

   info • 'primary' is deprecated and shouldn't be used. Use backgroundColor instead. This feature was deprecated after v3.1.0. • lib/components/buttons.dart:29:15 • deprecated_member_use
```

**Comment by saentari** [comment]
flutter analyze! How could I forget? Hopefully, this was the last unpleasant surprise.

**Review by vincenzopalazzo — APPROVED** [review]
Thanks!

Let give the time to the CI to finish and I will merge it :)

**Pull request merged**
