### PR TITLE
feat: invoice generation UI and logic

### LINKED ISSUE #67: Implement basic request view for generating inovice
# Background

The application now is not able to show to generate a request payment (aka bolt 11), so this mini project is using the current architecture to propose a workable solution that allow to form the following use case

1 Required an invoice with the following command https://lightning.readthedocs.io/lightning-invoice.7.html 
    1.1 Required all the required input from the user in a well defined UI
    1.2 Make the request to core lightning, and get back the response
    1.3 show the response in a QRCode by using the following package https://github.com/theyakka/qr.flutter

# Goal

Implement basic screen which takes useful inputs to generate invoice. Primiraly there are 3 input fields `amount_msat, label, description`. Feel free to checkout docs and add more optional fields(https://lightning.readthedocs.io/lightning-invoice.7.html)

After the user enters all the 3 fields and requests to generate an Invoice a QR code should be displayed.

I am hereby attaching some raw UI for the requested view reference

image

image

image

## End Goal

The final goal of this project is to be able to require from a remote node invoice and show it to the screen, and the solution needs to be workable and a well-developed solution following all the standards of flutter that need to work on all the platforms

### PR DESCRIPTION
**Pull request by mdmohsin7**
Added the ability to generate invoice from the provided label, description and amount. Created UI to view the generated invoice in the form of QR Code. Some functionality is still work in progress.

Should fix #67 and #94

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
the CI is failing 

```
Run flutter analyze .
Analyzing lndart.clnapp...                                      

warning • The '!' will have no effect because the receiver can't be null • lib/views/generate_invoice/invoice_details_view.dart:29:53 • unnecessary_non_null_assertion
warning • The '!' will have no effect because the receiver can't be null • lib/views/generate_invoice/invoice_details_view.dart:31:38 • unnecessary_non_null_assertion
```

but I am not happy with how the UI looks like, we are working with @Harshit933 in a figma, so you want to check out it here https://www.figma.com/file/394dxwuAPcZnOb2vaEBEjF/CLN-APP?node-id=0-1&t=VvhX2Ps7KYNQRx0z-0

**Comment by mdmohsin7** [comment]
> the CI is failing
> 
> ```
> Run flutter analyze .
> Analyzing lndart.clnapp...                                      
> 
> warning • The '!' will have no effect because the receiver can't be null • lib/views/generate_invoice/invoice_details_view.dart:29:53 • unnecessary_non_null_assertion
> warning • The '!' will have no effect because the receiver can't be null • lib/views/generate_invoice/invoice_details_view.dart:31:38 • unnecessary_non_null_assertion
> ```
> 
> but I am not happy with how the UI looks like, we are working with @Harshit933 in a figma, so you want to check out it here https://www.figma.com/file/394dxwuAPcZnOb2vaEBEjF/CLN-APP?node-id=0-1&t=VvhX2Ps7KYNQRx0z-0

Yes I made the temporary UI just to test the functionality, that is to see whether it is working as expected or not. I had a look at the Figma file and I have requested edit access for it so that I can contribute to it as well.

**Comment by Harshit933** [comment]
@mdmohsin7 given you the edit access. You can now contribute!

**Comment by vincenzopalazzo** [comment]
this is implemented with the figma design in https://github.com/dart-lightning/lndart.clnapp/pull/109

Thanks to open the PR anyway :)

**Pull request closed without merging**
