### PR TITLE
Fixes issue #98 added splashscreen

### PR DESCRIPTION
**Pull request by Ashurajput02**
### Pull Request Title
feat(clnapp): fixes issue #98

### Description
1.Added a SplashScreen which runs fine on both Iphone and Android.
2.Updated the kotlin version to the latest one under Android/gradle 

### Checklist
- [x] I have tested my changes
- [x] I have updated the documentation
- [x] I have added necessary comments

### Screenshots (if applicable)

Android:

https://github.com/dart-lightning/lndart.clnapp/assets/119595975/5f7608bb-91ff-4523-8d89-de6f0c9c71cd

<br>

Iphone:
Simulator Screenshot - iPhone 15 Pro Max - 2024-03-16 at 15 46 41
Simulator Screenshot - iPhone 15 Pro Max - 2024-03-16 at 15 46 39

---

### Commits
- `feat(clnapp): fixes issue #98`
  - Added a splash screen in the app .
  - The splash screen now consists of the app logo, a cool tagline on a light blue background.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
The splesh screen need to respect our theme color

**Comment by Ashurajput02** [comment]
> The splesh screen need to respect our theme color

So,I need to change: 
1.the background color from Light Blue to backgroundColor: Theme.of(context).colorScheme.background,
 2.and the text color from white to default.
 
Between is the tag line good?

**Comment by Ashurajput02** [comment]
> The splesh screen need to respect our theme color


https://github.com/dart-lightning/lndart.clnapp/assets/119595975/3d0ffdeb-e313-4172-8760-fb197a5afd77

This will be the result after making the changes in color from sky blue to primary background
Hope this one matches CLN app's theme

**Comment by vincenzopalazzo** [comment]
on the web is still blue https://deploy-preview-144--clnapp.netlify.app/

**Comment by Ashurajput02** [comment]
Yes because I have not yet pushed the changes . I just thought to ask is this one perfect so that I can create a fresh pull request for the same

**Comment by vincenzopalazzo** [comment]
idk I still do not like how it looks, it is a standard usage of the splash screen

**Comment by Ashurajput02** [comment]
. 

> idk I still do not like how it looks, it is a standard usage of the splash screen

May be we can use an animated spark coming down instead of a simple logo of the app. 
I mean instead of simple logo, it comes as an animated spark of electricity and then comes the test after a delay  And then a circle  showing loading.

**Comment by vincenzopalazzo** [comment]
I do not want to add a splash screen at this moment because the application UI sucks anyway. So I am closing this PR because there are issue more important to fix.

Thanks for contributing

**Pull request closed without merging**
